[global]
# Theme to use for light mode - default themes: autumn, default
theme = "documentation-light"
# Theme to use for dark mode - default themes: night, default-dark
theme_dark = "documentation-dark"
# Primary color for accents and highlights
colour = "#FFFFFF"
# Your website's name, displayed in various places
site_name = "Cynthia Mini Documentation"
# A brief description of your website
site_description = "Documentation for usage, or contribution to Cynthia Mini"

[server]
# Port number for the web server
port = 3000
# Host address for the web server
host = "localhost"


[integrations]
# Enable git integration for the website
# This will allow Cynthia Mini to detect the git repository
# For example linking to the commit hash in the footer
git = true


# Enable sitemap generation
# This will generate a sitemap.xml file in the root of the website
# 
# You will need to enter the base URL of your website in the sitemap variable below.
# If your homepage is at \"https://example.com/#/\", then the sitemap variable should be set to \"https://example.com\".
# If you do not want to use a sitemap, set this to \"false\", or leave it empty (\"\"), you can also remove the sitemap variable altogether.
sitemap = "https://strawmelonjuice.com"

# Enable crawlable context (JSON-LD injection)
# This will allow search engines to crawl the website, and makes it
# possible for the website to be indexed by search engine and LLMs.
crawlable_context = true


[posts]
# Enable comments on posts using utteranc.es
# Format: "username/repositoryname"
#
# You will need to give the utterances bot access to your repo.
# See https://github.com/apps/utterances to add the utterances bot to your repo
comment_repo = "CynthiaWebsiteEngine/Mini-docs"
