name: Continuous Integration

# This action works with pull requests and pushes on the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    name: Prettier fmt check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prettier, please!
        # You may pin to the exact commit or the version.
        # uses: reiddraper/prettier-please@78c10c34c7c783e9ff98d49a6aaa9b015f4381f2
        uses: reiddraper/prettier-please@v0.0.1
        with:
          # GitHub token
          github-token: ${{ secrets.GITHUB_TOKEN }}
